server:
  port: 8004
  #servlet:
    #context-path: /protected-service
         
external:
  property: hello universe
  version: 1.0.0

management:
  server:
    port: 9004
    servlet:
      context-path: /api/management
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: "*"
        
eureka:
  instance:
    homePageUrl: http://localhost:8000        
       